# Generated by Django 3.2.5 on 2021-07-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('order_by', models.IntegerField()),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('Diary', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Launch_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'live'), ('0', 'Pending'), ('-1', 'Archived')], default='1', max_length=10)),
            ],
        ),
    ]
